name: pod-chat
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - pip==24.3.1
  - pip:
      - black==24.10.0
      - streamlit==1.41.1
      - langchain==0.3.15
      - langchain-core==0.3.31
      - langchain-community==0.3.15
      - langchain-openai==0.3.1
      - duckduckgo-search==7.2.1
      - beautifulsoup4==4.12.3
      - youtube-transcript-api==0.6.3
      - pytube==15.0.0
      - tiktoken==0.8.0
      - nltk==3.9.1
      - sumy==0.11.0
      - huggingface-hub==0.27.1
